apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ollama-metrics
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
