apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: HEAD
    path: clusters/default/apps/llama-cpp
  destination:
    server: https://kubernetes.default.svc
    namespace: llama-cpp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
